Moves the orc8r-libs to its own repo
canonical/magma-orc8r-libs pull request #1
Opened 2022-06-15 17:39 UTC by gruyaume

Moves the orc8r-libs code from main charmed-magma project to its own repository. There is no code change from the original libs.

2022-07-20 18:33 UTC, ghislainbourgeois requested changes

2022-07-20 18:33 UTC, ghislainbourgeois commented on tests/test_orc8r_base_charm/src/charm.py
> +from charms.observability_libs.v0.kubernetes_service_patch import KubernetesServicePatch
Can you please update this to `v1`?

2022-07-20 18:33 UTC, ghislainbourgeois commented on tests/test_orc8r_base_db_charm/src/charm.py
> +from charms.observability_libs.v0.kubernetes_service_patch import KubernetesServicePatch
Can you please update this to `v1`?

2022-07-20 18:33 UTC, ghislainbourgeois commented on tox.ini
> +commands =
This will fix static analysis with latest version of mypy.
```suggestion
    types-toml
setenv =
    PYTHONPATH = ""
commands =
```

2022-07-20 18:33 UTC, ghislainbourgeois commented on lib/charms/observability_libs/v0/kubernetes_service_patch.py
> +# Copyright 2021 Canonical Ltd.
Can you please update this to `v1`

2022-08-23 20:08 UTC, gruyaume commented
I'll close this for now as it is too much behind the current version of the libs

2022-08-23 20:08 UTC, closed without merging