Telco 309 adds upgrade support for charms
canonical/magma-orc8r-libs pull request #6
Opened 2023-03-10 09:43 UTC by Gmerold

Adds handling for `upgrade_charm` hook.

2023-03-10 11:10 UTC, sanchezfdezjavier commented on tests/test_orc8r_base.py
> +    def test_given_relation_created_but_not_ready_when_upgrade_charm_then_status_is_blocked(self):
```suggestion
    def test_given_relation_created_but_not_ready_when_upgrade_charm_then_status_is_waiting(self):
```

2023-03-10 11:15 UTC, sanchezfdezjavier commented on tests/test_orc8r_base_db.py
> +        )
Is there any reason why here we're using `assert == whatever` instead of `self.assertEqual`, the second one provides a meaningful output if the assertion fails.

2023-03-10 11:16 UTC, sanchezfdezjavier commented on tests/test_orc8r_base_db.py
> +        )
Same as above.

2023-03-10 11:24 UTC, sanchezfdezjavier commented on tests/test_orc8r_base_db.py
> +        key_values = {"master": self.TEST_DB_CONNECTION_STRING.__str__()}
Why are we calling a dunder method instead of the regular one like `str(TEST_DB_CONNECTION_STRING)`? I guess it's the exact same result, I thought those were supposed to be called internally by Python

2023-03-10 11:31 UTC, sanchezfdezjavier commented on lib/charms/magma_orc8r_libs/v0/orc8r_base.py
> +        environment_variables.update(self.additional_environment_variables)
Nitpicking, we can use the union operator for merging dictionaries. Like this 
```suggestion
        environment_variables |= self.additional_environment_variables
```
https://peps.python.org/pep-0584/

2023-03-10 11:35 UTC, sanchezfdezjavier commented on lib/charms/magma_orc8r_libs/v0/orc8r_base.py
>              self.additional_environment_variables = {}
This is not from your PR, but I think this might be better
```suggestion
       self.additional_environment_variables = additional_environment_variables or {}
```

2023-03-10 11:53 UTC, Gmerold commented on tests/test_orc8r_base_db.py
> +        )
Not sure what you mean. Both produce similar output, essentially saying that the assertion failed.
As for the reason, I reused existing tests for writing new ones, that's why the use this assertion method.

2023-03-10 11:54 UTC, Gmerold commented on lib/charms/magma_orc8r_libs/v0/orc8r_base.py
> +        environment_variables.update(self.additional_environment_variables)
I think `.update` is way easier to understand :)

2023-03-10 11:58 UTC, Gmerold commented on tests/test_orc8r_base.py
> +    def test_given_relation_created_but_not_ready_when_upgrade_charm_then_status_is_blocked(self):
Fixed.

2023-03-10 11:58 UTC, Gmerold commented on lib/charms/magma_orc8r_libs/v0/orc8r_base.py
>              self.additional_environment_variables = {}
I like that. Changed.

2023-03-10 12:00 UTC, Gmerold commented on tests/test_orc8r_base_db.py
> +        key_values = {"master": self.TEST_DB_CONNECTION_STRING.__str__()}
I reused existing tests and I haven't really thought why was it like that in the first pleace.
Changed it as you suggested tho.

2023-03-10 12:09 UTC, sanchezfdezjavier commented on tests/test_orc8r_base_db.py
> +        )
If you have 
```python
def test_example(self):
        foo = 1
        bar = 2
        self.assertEqual(foo, bar)
```

The first will fail like
```bash
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    assert foo == bar
AssertionError
```

And the second like
```bash
======================================================================
FAIL: test_example (__main__.TestExample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "example.py", line 8, in test_example
    self.assertEqual(foo, bar)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 1 test in 0.000s
```

In this case for this test is not a big deal, still the second explains the reason of the failure.

2023-03-10 12:11 UTC, sanchezfdezjavier commented on lib/charms/magma_orc8r_libs/v0/orc8r_base.py
> +        environment_variables.update(self.additional_environment_variables)
Yeah, I agree. It is in PEP so it was worth mentioning.

2023-03-10 12:17 UTC, Gmerold commented on tests/test_orc8r_base_db.py
> +        )
Yeah, but if you run them with tox, as we do, the you have:
```python
@patch("subprocess.check_call")
def test_given_db_relation_not_ready_when_upgrade_charm_then_status_is_blocked(
        self, patched_check_call
):
    patched_check_call.return_value = "whatever"
    self.harness.add_relation(relation_name="db", remote_app="postgresql-k8s")

    self.harness.charm.on.upgrade_charm.emit()

    assert self.harness.charm.unit.status == WaitingStatus(
        "Waiting for db relation to be ready test"
    )
```
```shell
_________________________________________________________________________ TestCharm.test_given_db_relation_not_ready_when_upgrade_charm_then_status_is_blocked _________________________________________________________________________
Traceback (most recent call last):
  File "/home/gmerold/REPOS/magma-orc8r-libs/tests/test_orc8r_base_db.py", line 275, in test_given_db_relation_not_ready_when_upgrade_charm_then_status_is_blocked
    assert self.harness.charm.unit.status == WaitingStatus(
AssertionError: assert WaitingStatus('Waiting for db relation to be ready') == WaitingStatus('Waiting for db relation to be ready test')
 +  where WaitingStatus('Waiting for db relation to be ready') = <ops.model.Unit magma-orc8r-dummy/0>.status
 +    where <ops.model.Unit magma-orc8r-dummy/0> = <ops.testing.Harness.begin.<locals>.TestCharm object at 0x7f96c53d3be0>.unit
 +      where <ops.testing.Harness.begin.<locals>.TestCharm object at 0x7f96c53d3be0> = <ops.testing.Harness object at 0x7f96c53d2e90>.charm
 +        where <ops.testing.Harness object at 0x7f96c53d2e90> = <test_orc8r_base_db.TestCharm testMethod=test_given_db_relation_not_ready_when_upgrade_charm_then_status_is_blocked>.harness
 +  and   WaitingStatus('Waiting for db relation to be ready test') = WaitingStatus('Waiting for db relation to be ready test')

```
and
```shell
======================================================================================================= short test summary info ========================================================================================================
FAILED tests/test_orc8r_base_db.py::TestCharm::test_given_db_relation_not_ready_when_upgrade_charm_then_status_is_blocked - AssertionError: assert WaitingStatus('Waiting for db relation to be ready') == WaitingStatus('Waiting for db relation to be ready test')
```

Whereas 
```python
@patch("subprocess.check_call")
def test_given_db_relation_not_ready_when_upgrade_charm_then_status_is_blocked(
    self, patched_check_call
):
    patched_check_call.return_value = "whatever"
    self.harness.add_relation(relation_name="db", remote_app="postgresql-k8s")

    self.harness.charm.on.upgrade_charm.emit()

    self.assertEqual(
        self.harness.charm.unit.status,
        WaitingStatus("Waiting for db relation to be ready test"),
    )
```
produces
```bash
_________________________________________________________________________ TestCharm.test_given_db_relation_not_ready_when_upgrade_charm_then_status_is_blocked _________________________________________________________________________
Traceback (most recent call last):
  File "/home/gmerold/REPOS/magma-orc8r-libs/tests/test_orc8r_base_db.py", line 275, in test_given_db_relation_not_ready_when_upgrade_charm_then_status_is_blocked
    self.assertEqual(
  File "/usr/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.10/unittest/case.py", line 838, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: WaitingStatus('Waiting for db relation to be ready') != WaitingStatus('Waiting for db relation to be ready test')
```
and 
```bash
======================================================================================================= short test summary info ========================================================================================================
FAILED tests/test_orc8r_base_db.py::TestCharm::test_given_db_relation_not_ready_when_upgrade_charm_then_status_is_blocked - AssertionError: WaitingStatus('Waiting for db relation to be ready') != WaitingStatus('Waiting for db relation to be ready test')
```

2023-03-10 12:21 UTC, sanchezfdezjavier commented on tests/test_orc8r_base_db.py
> +        )
Good point, resolved.

2023-03-10 12:22 UTC, sanchezfdezjavier approved these changes
LGTM

2023-03-10 14:59 UTC, ghislainbourgeois requested changes

2023-03-10 14:59 UTC, ghislainbourgeois commented on lib/charms/magma_orc8r_libs/v0/orc8r_base.py
> +        self.framework.observe(pebble_ready_event, self._configure_workload)
Bump libpatch?

2023-03-10 14:59 UTC, ghislainbourgeois commented on lib/charms/magma_orc8r_libs/v0/orc8r_base_db.py
> +        self.framework.observe(pebble_ready_event, self._configure_workload)
Bump libpatch?

2023-03-13 07:59 UTC, Gmerold commented on lib/charms/magma_orc8r_libs/v0/orc8r_base.py
> +        self.framework.observe(pebble_ready_event, self._configure_workload)
Done.

2023-03-13 08:00 UTC, Gmerold commented on lib/charms/magma_orc8r_libs/v0/orc8r_base_db.py
> +        self.framework.observe(pebble_ready_event, self._configure_workload)
Done.

2023-03-14 08:14 UTC, merged